apiVersion: v1
metadata:
  name: snotest
baseDomain: demo.red-chesterfield.com
imageContentSources:
- mirrors:
  - quay.io:443/acm-d
  source: registry.redhat.io/rhacm2
- mirrors:
  - registry.redhat.io/openshift4/ose-oauth-proxy
  source: registry.access.redhat.com/openshfit4/ose-oauth-proxy
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.2xlarge
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
pullSecret: ""
sshKey: |-
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD2hBmH2vwWr9F1RsSyCxpy8gNdzXujmzCQFPWofXZRz5tWfEYkmlWs5MvpF5nk3bDQxt6Qt+A0YEbt4izgjtYac6EHd6LjbDvASooeEmZpr1pCzR8re8x8WYomjuWdcDmjOIEbRv5XF5l2M4VGbkKResXa96W7co7Luh3s5+9XIjEKF4Ol1Lkb68tF6L0SY8sSA4uqTFN3w878P8SbMHeA2XbWDPZ0Y+EVMWQ8BoT3iF+lTax8Qh0nrZd3DMqoEH+K58Q/Cij5Th+u/IFaU0bo2UfiOpGf+d2V+GSe5qE5anW49lK8hZqTw3ZuFR+aU+LfkUEuuQYeInjIYr/sgJeWB/PmwX4IrCKQTMfhqo4GbS30Sc2UpTuW+Bx+RC97jtFvOKAWxp1XJ07/6xAsNtX5bch2FdoeCWcQL2LwmZzScICQcXVd/czfW3PDiACCerSMWWrqXbjj+mAfCX1x6+U/kky2O8OtBV/KjFDZcod6+0WU1UPH/c7Nw406BmRW+mIq1Uqtj7vm1MravgHn5ZAejS7S7mJlDPcFjl+o5LEBbEvXY2TpwhGioZoldchdevQgOrmRkeWgpuT0nSBcTEnt6xLVs1vAH0IxS+aMgUQpN6wGMv3LszgYR/0wcAQ9evHCisSwInkoIWXIj+mr3LzoePpSfmMl4AiN6EjW8Uw21Q== example@example.com
