---

- fail:
    msg: "Only set one of kubernetes_context or openshift_host"
  when: openshift_host is defined and kubernetes_context is defined

- include_tasks: "{{ tasks }}"
  with_items:
    - openshift_auth.yml
  loop_control:
    loop_var: tasks
  when: openshift_host is defined

- name: Use kubectl or oc
  set_fact:
    kubectl_or_oc: "{{ openshift_oc_bin if openshift_oc_bin is defined else 'kubectl' }}"

- name: Clone the content repo
  git:
    repo: 'https://github.ibm.com/IBMPrivateCloud/sre-production-content.git'
    dest: "{{ kubernetes_base_path }}/sre-production-content"

- name: Apply Kubernetes resources
  shell: |
    {{ kubectl_or_oc }} apply -f {{ kubernetes_base_path }}/sre-production-content/scripts/resources/{{ item }}
  with_items:
    - "clusterimagepolicy"
    # - "policies"
  # no_log: yes