---

# - name: "Delete {{ SNO_CLUSTERIMAGESET_NAME }} clusterimageset"
#   community.kubernetes.k8s:
#     state: absent
#     definition: "{{ lookup('template', 'clusterimageset.yaml.j2') | from_yaml }}"
#   ignore_errors: yes

- name: "Create 4.8.0 CI clusterimageset"
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'clusterimageset.yaml.j2') | from_yaml }}"

- name: "Create 4.8.0 nightly clusterimageset"
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'clusterimageset-48-nightly.yaml.j2') | from_yaml }}"

- set_fact:
    installconfigyaml: "{{ lookup('template', 'install-config.yaml.j2') | from_yaml }}"
    HIVE_INSTALL_CONFIG: "{{ lookup('template', 'install-config.yaml.j2') | from_yaml | b64encode }}"
    installconfigraw: "{{ lookup('template', 'install-config.yaml.j2') }}"

- set_fact:
    clusteryaml: "{{ lookup('template', 'cluster-48-ci.yaml.j2') }}"
    manifestpath: ./clusterdeployment/config/{{ HIVE_CLUSTER_NAME }}

- name: installconfigyaml
  debug:
    msg: "{{ installconfigyaml }}"
  when: debug is defined

- name: installconfig
  debug:
    msg: "{{ installconfigraw.split('\n') }}"

- name: HIVE_INSTALL_CONFIG
  debug:
    msg: "{{ HIVE_INSTALL_CONFIG }}"

- name: Debug dry run cluster.yaml
  debug:
    msg: "{{ clusteryaml.split('\n') }}"

- name: Create {{ manifestpath }} folder
  ansible.builtin.file:
    path: "{{ manifestpath }}"
    state: directory
    mode: '0755'

- name: Create install-config.yaml
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "{{ manifestpath }}/install-config.yaml"
    mode: '0755'

- name: Create cluster.yaml
  ansible.builtin.template:
    src: cluster-48-ci.yaml.j2
    dest: "{{ manifestpath }}/cluster.yaml"
    mode: '0755'

- name: Create cluster.yaml
  ansible.builtin.template:
    src: cluster-48-nightly.yaml.j2
    dest: "{{ manifestpath }}/cluster-48-nightly.yaml"
    mode: '0755'

- name: "Manual trigger cluster provision ..."
  debug:
    msg:
    - "oc new-project {{ HIVE_CLUSTER_NAME }}"
    - "oc apply -f {{ manifestpath }}/cluster.yaml"
